const matches = 
[
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'Rayo Vallecano',
    away: 'Atletico Madrid',
    bet: 'Atletico Madrid ou Nul',
    prob: '83%',
    rating: '26%/74%',
    color: 'badge-safe',
    scenario: 'L\'Atletico devrait dominer techniquement face à un Rayo en crise, mais la fatigue européenne des Colchoneros pourrait freiner une victoire large.',
    trap: 'La fatigue accumulée par l\'Atletico après son exploit en Coupe (4-0 vs Barça) face à un adversaire qui joue sa survie.',
    score: '0-1',
    logic: 'Les statistiques montrent une probabilité de 83% pour le cumul Nul ou Victoire (28% + 55%), ce qui confirme l\'analyse de la fatigue des jambes nécessitant une couverture DNB.'
  },
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'Real Oviedo',
    away: 'Athletic Club',
    bet: 'Moins de 3.5 buts',
    prob: '73.5%',
    rating: '26%/74%',
    color: 'badge-safe',
    scenario: 'Un match fermé où Oviedo tentera de verrouiller le score face à des Basques émoussés par leur demi-finale de Coupe.',
    trap: 'Oviedo est reposé (15 jours sans match) et très solide à domicile, contrastant avec l\'usure physique de l\'Athletic.',
    score: '0-1 ou 1-1',
    logic: 'Les statistiques montrent une probabilité de 73.5% pour le Under 3.5, ce qui confirme l\'analyse d\'un match pauvre en buts dû à l\'anémie offensive locale et la fatigue visiteuse.'
  },
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'Levante',
    away: 'Valencia',
    bet: 'Moins de 3.5 buts',
    prob: '72.7%',
    rating: '42%/58%',
    color: 'badge-safe',
    scenario: 'Un derby valencien verrouillé où la tension et la peur de perdre devraient limiter les prises de risques offensives.',
    trap: 'L\'agressivité habituelle de Levante à domicile contre un Valence friable à l\'extérieur pourrait emballer le match si un but arrive tôt.',
    score: '1-1',
    logic: 'Les statistiques montrent une probabilité de 72.7% pour le Under 3.5, ce qui confirme l\'analyse d\'un derby haché et tactiquement fermé.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'FC Augsburg',
    away: '1. FC Heidenheim',
    bet: 'Plus de 1.5 buts',
    prob: '72%',
    rating: '65%/35%',
    color: 'badge-safe',
    scenario: 'Augsburg imposera son rythme offensif habituel à domicile face à un Heidenheim capable de punir en contre-attaque.',
    trap: 'L\'irrégularité chronique d\'Augsburg peut rendre le résultat final aléatoire malgré leur supériorité statistique.',
    score: '2-1',
    logic: 'Les statistiques montrent une forte probabilité de buts (72% pour l\'over 1.5), ce qui confirme le profil de "portes ouvertes" des deux formations.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'RB Leipzig',
    away: 'VfL Wolfsburg',
    bet: 'Victoire RB Leipzig',
    prob: '69%',
    rating: '73%/27%',
    color: 'badge-safe',
    scenario: 'Leipzig devrait étouffer Wolfsburg par son pressing haut et son efficacité offensive à la Red Bull Arena.',
    trap: 'La propension de Wolfsburg à surprendre en contre-attaque malgré une forme globale déclinante.',
    score: '3-0',
    logic: 'Les statistiques montrent une domination globale nette (73%), ce qui confirme la solidité de la forteresse de Leipzig face à une défense adverse fragile.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Udinese',
    away: 'Sassuolo',
    bet: 'Udinese ou Nul',
    prob: '74%',
    rating: '52%/48%',
    color: 'badge-safe',
    scenario: 'L\'Udinese imposera son bloc rigoureux pour neutraliser un Sassuolo trop déséquilibré défensivement en déplacement.',
    trap: 'La tendance de l\'Udinese à concéder des nuls (Rois du Nul) empêche de garantir une victoire sèche.',
    score: '1-1',
    logic: 'Les statistiques montrent 74% de chances pour le 1N (40%+34%), ce qui confirme la difficulté historique de battre l\'Udinese au Friuli.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Cremonese',
    away: 'Genoa',
    bet: 'Genoa ou Nul',
    prob: '74%',
    rating: '43%/57%',
    color: 'badge-safe',
    scenario: 'Un match de survie où le Genoa, plus créatif, devrait dominer une équipe de Cremonese totalement stérile offensivement.',
    trap: 'Cremonese a remporté le match aller (0-2), créant un ascendant psychologique malgré leur forme actuelle catastrophique.',
    score: '0-1',
    logic: 'Les statistiques montrent un avantage global au Genoa, ce qui confirme l\'incapacité de Cremonese à marquer face à une équipe mieux organisée.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Parma',
    away: 'Hellas Verona',
    bet: 'Parma ou Nul',
    prob: '73%',
    rating: '54%/47%',
    color: 'badge-safe',
    scenario: 'Parme utilisera sa solidité au Stadio Tardini pour contenir une équipe de Vérone inoffensive loin de ses bases.',
    trap: 'Un match qui risque d\'être haché par les fautes, limitant les occasions de but des deux côtés.',
    score: '1-0',
    logic: 'Les statistiques montrent 73% pour la double chance locale, ce qui confirme la faiblesse récurrente du Hellas en voyage.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Torino',
    away: 'Bologna',
    bet: 'Moins de 2.5 buts',
    prob: '54.3%',
    rating: '37%/63%',
    color: 'badge-warning',
    scenario: 'Duel tactique intense entre deux blocs compacts qui privilégieront la structure défensive au détriment du spectacle.',
    trap: 'La supériorité technique de Bologne pourrait forcer le verrou si le Torino se déconcentre sur un coup de pied arrêté.',
    score: '0-0',
    logic: 'Les statistiques montrent un Under 2.5 probable, ce qui confirme l\'analyse d\'une "guerre de tranchées" tactique typique de ces deux clubs.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Napoli',
    away: 'AS Roma',
    bet: 'Moins de 3.5 buts',
    prob: '80%',
    rating: '53%/47%',
    color: 'badge-safe',
    scenario: 'Un choc au sommet où la meilleure défense d\'Italie (Roma) fera face à un Napoli solide mais prudent.',
    trap: 'Le talent individuel des attaquants napolitains pourrait faire exploser le verrou romain en cas d\'ouverture rapide du score.',
    score: '1-0',
    logic: 'Les statistiques prévoient 80% de chances pour moins de 4 buts, ce qui confirme la tendance récente des duels très fermés entre ces deux rivaux.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Cagliari',
    away: 'Lecce',
    bet: 'Cagliari ou Nul',
    prob: '80%',
    rating: '61%/39%',
    color: 'badge-safe',
    scenario: 'Cagliari jouera sur son agressivité à domicile pour prendre des points vitaux face à un Lecce quasi-inoffensif à l\'extérieur.',
    trap: 'La peur de perdre ce match à 6 points pourrait paralyser Cagliari et mener à un match nul stérile.',
    score: '1-0',
    logic: 'Les statistiques montrent une domination de Cagliari (61%), ce qui confirme leur statut d\'équipe intraitable face aux concurrents directs à l\'Unipol Domus.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'Le Havre',
    away: 'Toulouse',
    bet: 'Moins de 3.5 buts',
    prob: '76.9%',
    rating: '44%/56%',
    color: 'badge-safe',
    scenario: 'Le Havre va ériger un mur défensif au Stade Océane pour frustrer des Toulousains souvent en difficulté face aux blocs bas.',
    trap: 'Toulouse possède des individualités capables de débloquer la situation, mais Le Havre perd rarement pied chez lui.',
    score: '1-1',
    logic: 'Les statistiques montrent 76.9% pour le Under 3.5, ce qui confirme la nature de "forteresse béton" du HAC à domicile.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'Lorient',
    away: 'Angers',
    bet: 'Lorient ou Nul',
    prob: '84%',
    rating: '56%/44%',
    color: 'badge-safe',
    scenario: 'Lorient devrait dominer territorialement face à un Angers laborieux, mais le bloc compact angevin pourrait accrocher un partage des points.',
    trap: 'L\'historique H2H (50/50) contredit la forme actuelle étincelante de Lorient (4V sur 5).',
    score: '2-1 ou 1-1',
    logic: 'Les statistiques montrent une probabilité de 84% pour le 1N (52%+32%), ce qui confirme l\'analyse de la forteresse du Moustoir face à un visiteur inoffensif.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'Lyon',
    away: 'Nice',
    bet: 'Lyon ou Nul',
    prob: '86%',
    rating: '69%/31%',
    color: 'badge-safe',
    scenario: 'L\'OL cherchera à faire exploser le verrou niçois dès l\'entame, porté par une dynamique de 5 victoires consécutives.',
    trap: 'Le bloc "béton" de Nice est l\'un des meilleurs du championnat et pourrait frustrer l\'attaque flamboyante de Lyon.',
    score: '2-1',
    logic: 'Les statistiques montrent une supériorité offensive nette (70%), ce qui confirme l\'analyse d\'une invincibilité lyonnaise au Groupama Stadium.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'Metz',
    away: 'Auxerre',
    bet: 'Metz ou Nul',
    prob: '68%',
    rating: '30%/70%',
    color: 'badge-warning',
    scenario: 'Un duel tactique où Metz tentera de piéger une équipe d\'Auxerre techniquement supérieure mais souvent naïve à l\'extérieur.',
    trap: 'La statistique H2H (93% pour Auxerre) est en totale contradiction avec la difficulté historique de gagner à Saint-Symphorien.',
    score: '1-1',
    logic: 'Les statistiques montrent un équilibre sur le match nul (34%), ce qui confirme l\'analyse privilégiant la solidité messine à domicile.'
  },
  {
    league: 'ENG',
    leagueFull: 'FA Cup',
    home: 'Birmingham',
    away: 'Leeds',
    bet: 'Plus de 1.5 buts',
    prob: '72%',
    rating: '56%/44%',
    color: 'badge-danger',
    scenario: 'Un match de coupe intense où le pressing haut de Leeds forcera des espaces, obligeant Birmingham à répondre physiquement.',
    trap: 'Contradiction forte : l\'IA donne Birmingham favori (50%) alors que la hiérarchie technique favorise nettement Leeds.',
    score: '1-2',
    logic: 'Les statistiques montrent un scénario de duel offensif (100% BTTS selon l\'IA), ce qui confirme l\'analyse du volume de buts inhérent au style de Leeds.'
  },
  {
    league: 'ENG',
    leagueFull: 'FA Cup',
    home: 'Grimsby',
    away: 'Wolves',
    bet: 'Plus de 1.5 buts',
    prob: '77%',
    rating: '43%/57%',
    color: 'badge-danger',
    scenario: 'Le "Petit Poucet" Grimsby tentera l\'exploit dans son stade hostile, mais l\'écart de trois divisions devrait finir par se voir.',
    trap: 'Divergence extrême : l\'IA prévoit une victoire de Grimsby (64%) tandis que la logique sportive impose une domination des Wolves.',
    score: '1-2 ou 0-2',
    logic: 'Les statistiques montrent un potentiel de match prolifique (83% BTTS), ce qui confirme l\'analyse sur l\'écart de vitesse d\'exécution entre les deux ligues.'
  },
  {
    league: 'ENG',
    leagueFull: 'FA Cup',
    home: 'Oxford United',
    away: 'Sunderland',
    bet: 'Sunderland ou Nul',
    prob: '87%',
    rating: '35%/65%',
    color: 'badge-safe',
    scenario: 'Sunderland devrait monopoliser le ballon face à un bloc d\'Oxford très bas qui jouera le contre pour arracher un replay.',
    trap: 'La défaite de Sunderland en avril dernier contre ce même adversaire peut peser mentalement.',
    score: '0-2',
    logic: 'Les statistiques donnent 87% de chances au X2 (59%+28%), ce qui confirme l\'analyse de la supériorité technique des Black Cats.'
  },
  {
    league: 'ENG',
    leagueFull: 'FA Cup',
    home: 'Stoke City',
    away: 'Fulham',
    bet: 'Fulham ou Nul',
    prob: '86%',
    rating: '38%/62%',
    color: 'badge-safe',
    scenario: 'Fulham devrait imposer sa supériorité technique dès l\'entame face à un Stoke solide physiquement mais limité dans la création.',
    trap: 'La nature imprévisible de la coupe à domicile pour Stoke (Bet365 Stadium) face à une équipe de Fulham parfois gestionnaire.',
    score: '1-2',
    logic: 'Les statistiques montrent une probabilité cumulée de 86% pour le X2 (58% + 28%), ce qui confirme l\'analyse de la supériorité technique intrinsèque des Cottagers.'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'Feyenoord',
    away: 'GO Ahead Eagles',
    bet: 'Victoire Feyenoord',
    prob: '73%',
    rating: '78%/22%',
    color: 'badge-safe',
    scenario: 'Une domination totale attendue de Feyenoord dans l\'enfer de De Kuip face à des Eagles qui peinent historiquement face au Big 3.',
    trap: 'L\'excès de confiance face à une équipe courageuse qui cherchera à geler le jeu le plus longtemps possible.',
    score: '3-0',
    logic: 'Les statistiques montrent un avantage global de 78%, ce qui confirme l\'analyse d\'une "machine offensive" trop puissante pour l\'adversaire.'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'Heerenveen',
    away: 'PEC Zwolle',
    bet: 'Plus de 2.5 buts',
    prob: '63%',
    rating: '52%/48%',
    color: 'badge-warning',
    scenario: 'Un match ouvert typique du football néerlandais où les deux défenses perméables devraient laisser place à un festival offensif.',
    trap: 'Une soudaine rigueur défensive d\'Heerenveen à domicile pour compenser leur forme fragile.',
    score: '2-2',
    logic: 'Les statistiques montrent une tendance offensive marquée (63% sur l\'indicateur buts), ce qui confirme l\'analyse d\'une zone "feu d\'artifice" sans verrou défensif.'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'Telstar',
    away: 'Twente',
    bet: 'Victoire Twente',
    prob: '51%',
    rating: '26%/74%',
    color: 'badge-warning',
    scenario: 'Twente devrait faire respecter la hiérarchie en imposant son bloc rigoureux face à un Telstar en lutte pour le maintien.',
    trap: 'Le vent et l\'ambiance particulière du BUKO Stadion qui peuvent niveler les valeurs techniques.',
    score: '0-2',
    logic: 'Les statistiques montrent une domination écrasante dans l\'historique H2H (91%), ce qui confirme l\'analyse de l\'écart de classe entre les deux effectifs.'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'Sparta Rotterdam',
    away: 'NEC Nijmegen',
    bet: 'Sparta Rotterdam ou Nul',
    prob: '65%',
    rating: '56%/44%',
    color: 'badge-warning',
    scenario: 'Le "Kasteel" devrait jouer son rôle de forteresse face à une équipe de NEC audacieuse mais souvent trop fragile en déplacement.',
    trap: 'La forme étincelante de NEC (4V sur 5) qui pourrait briser la discipline tactique du Sparta.',
    score: '1-1',
    logic: 'Les statistiques montrent 65% de chances pour le 1X (37% + 28%), ce qui confirme l\'analyse de la solidité historique du Sparta à domicile.'
  },
  {
    league: 'TUR',
    leagueFull: 'Süper Lig',
    home: 'Kocaelispor',
    away: 'Gaziantep FK',
    bet: 'Kocaelispor ou Nul',
    prob: '51%',
    rating: '34%/66%',
    color: 'badge-danger',
    scenario: 'L\'ambiance électrique d\'Izmit devrait porter Kocaelispor face à des visiteurs techniquement supérieurs mais inconstants à l\'extérieur.',
    trap: 'Contradiction forte : l\'IA favorise Gaziantep (49%) tandis que le contexte local favorise la forteresse de Kocaelispor.',
    score: '1-1',
    logic: 'Les statistiques montrent un avantage théorique aux visiteurs, mais l\'analyse du terrain confirme la règle de la "Forteresse Domicile" turque.'
  }
]