const matches = 
[
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'Borussia Dortmund',
    away: 'FSV Mainz 05',
    bet: 'Victoire de Borussia Dortmund',
    prob: '63%',
    rating: '71/29',
    color: 'badge-safe',
    scenario: 'Dortmund impérial à domicile face à une défense passoire.',
    trap: 'Mayence reste sur 4 victoires, attention au contre.',
    score: '3-1 ou 2-1',
    logic: 'Dortmund (Attaque 71%) affronte une défense de Mayence notée à 26%. Malgré la forme récente des visiteurs, le xG de 2.05 du BVB et l\'écart technique garantissent la victoire.'
  },
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'Elche',
    away: 'Osasuna',
    bet: 'Osasuna ou Nul (Double Chance X2)',
    prob: '91%',
    rating: '38/62',
    color: 'badge-safe',
    scenario: 'Elche en crise totale face à un Osasuna solide.',
    trap: 'Attention à la ligne "Spectacle garanti", match fermé.',
    score: '0-1 ou 1-1',
    logic: 'Elche est en perdition (Forme 9%) face à Osasuna (Forme 91%). Avec des xG faibles et un match tactique, les visiteurs ne perdront pas.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Pisa',
    away: 'AC Milan',
    bet: 'Victoire de l\'AC Milan',
    prob: '62%',
    rating: '37/63',
    color: 'badge-safe',
    scenario: 'Milan bien supérieur face à une attaque de Pise muette.',
    trap: 'Ne pas jouer l\'Over, match maîtrisé type 0-1.',
    score: '0-2 ou 0-1',
    logic: 'Pisa a une attaque notée à 29% et un xG famélique de 0.64. Milan (Défense 65%) devrait s\'imposer sans encaisser grâce à l\'écart de classe.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'Rennes',
    away: 'Paris Saint-Germain',
    bet: 'Victoire du Paris Saint-Germain',
    prob: '69%',
    rating: '13/87',
    color: 'badge-safe',
    scenario: 'Naufrage défensif de Rennes face au rouleau compresseur PSG.',
    trap: 'Rennes pourrait marquer pour l\'honneur (BTTS 62%).',
    score: '1-3 ou 0-3',
    logic: 'Avec une défense à 7% et un Global Rating de 13%, Rennes ne peut rivaliser. Le PSG (Forme 91%, xG 2.56) va dérouler offensivement.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'AS Monaco',
    away: 'FC Nantes',
    bet: 'Victoire de l\'AS Monaco',
    prob: '69%',
    rating: '83/17',
    color: 'badge-safe',
    scenario: 'Nantes en chute libre (5 défaites) face à Monaco.',
    trap: 'Attention au relâchement une fois le score acquis.',
    score: '3-0 ou 2-0',
    logic: 'Nantes est en crise totale (Forme 12%, 5 défaites). Monaco (Global 83%) domine 85% des H2H et possède un xG dominant de 2.33.'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'FC Volendam',
    away: 'PSV Eindhoven',
    bet: 'Victoire du PSV Eindhoven',
    prob: '86%',
    rating: '26/74',
    color: 'badge-safe',
    scenario: 'Gouffre de classe : le PSV doit s\'imposer logiquement.',
    trap: 'Terrain synthétique et Volendam marque à domicile (BTTS 66%).',
    score: '1-3 ou 1-4',
    logic: 'Malgré une cote IA basse, le PSV est supérieur de 48 points (Global Rating). Avec 86% de victoires en H2H et une attaque à 74%, la victoire est impérative.'
  },
  {
    league: 'TUR',
    leagueFull: 'Süper Lig',
    home: 'Antalyaspor',
    away: 'Samsunspor',
    bet: 'Samsunspor ou Nul (Double Chance X2)',
    prob: '62%',
    rating: '39/61',
    color: 'badge-value',
    scenario: 'Antalyaspor inoffensif face à un Samsunspor solide.',
    trap: 'H2H favorable à Antalyaspor (60%), risque de nul.',
    score: '0-0, 0-1 ou 1-1',
    logic: 'Antalyaspor a une attaque faible (39%) et un xG de 0.84. Samsunspor est en meilleure forme (62%) et ne devrait pas perdre ce match fermé.'
  },
  {
    league: 'TUR',
    leagueFull: 'Süper Lig',
    home: 'Galatasaray',
    away: 'Eyüpspor',
    bet: 'Victoire de Galatasaray',
    prob: '89%',
    rating: '86/14',
    color: 'badge-safe',
    scenario: 'Démonstration attendue : 89% de probabilité pour Galatasaray.',
    trap: 'Aucun piège majeur, cote très basse.',
    score: '3-0 ou 4-0',
    logic: 'Record de la semaine avec 89% de probabilité. Galatasaray (Attaque 86%) affronte une défense à 14%. Le xG de 3.32 annonce une valise.'
  },
  {
    league: 'POR',
    leagueFull: 'Primeira Liga',
    home: 'Santa Clara',
    away: 'Benfica',
    bet: 'Victoire de Benfica',
    prob: '67%',
    rating: '17/83',
    color: 'badge-safe',
    scenario: 'Benfica domine sa bête noire (93% H2H).',
    trap: 'Santa Clara va défendre très bas.',
    score: '0-2 ou 0-3',
    logic: 'Santa Clara est en perdition (Forme 9%) et Benfica domine 93% des duels. Avec 66 points d\'écart au Global Rating, la victoire est indiscutable.'
  },
  {
    league: 'POR',
    leagueFull: 'Primeira Liga',
    home: 'CD Tondela',
    away: 'FC Alverca',
    bet: 'Alverca ou Nul (Double Chance X2)',
    prob: '87%',
    rating: '35/66',
    color: 'badge-value',
    scenario: 'Alverca bête noire historique : Value sur le X2.',
    trap: 'Tondela favori des cotes (erreur de marché).',
    score: '0-1 ou 1-1',
    logic: 'Tondela est en chute libre (Forme 22%) alors qu\'Alverca (Forme 78%) domine l\'historique (87%). L\'écart de niveau réel favorise largement les visiteurs.'
  },
  {
    league: 'SAU',
    leagueFull: 'Saudi Pro League',
    home: 'Al-Hilal Saudi FC',
    away: 'Al-Ettifaq',
    bet: 'Victoire d\'Al-Hilal',
    prob: '93%',
    rating: '70/30',
    color: 'badge-safe',
    scenario: 'Al-Hilal intouchable à domicile (H2H 93%).',
    trap: 'Al-Hilal reste sur 4 nuls, besoin de se rassurer.',
    score: '2-0 ou 3-0',
    logic: 'Malgré des nuls récents, Al-Hilal (Global 70%) est bien supérieur à Al-Ettifaq (30%). L\'historique (93% de victoires) garantit quasiment le résultat.'
  },
  {
    league: 'SAU',
    leagueFull: 'Saudi Pro League',
    home: 'Al-Ittihad FC',
    away: 'Al-Fayha',
    bet: 'Victoire d\'Al-Ittihad',
    prob: '85%',
    rating: '61/40',
    color: 'badge-safe',
    scenario: 'Al-Ittihad maître à domicile face à sa bête noire.',
    trap: 'Al-Fayha a de meilleures stats offensives récentes (60%).',
    score: '1-0 ou 2-0',
    logic: 'Al-Ittihad domine 85% des confrontations. Malgré une attaque moins flamboyante récemment, leur classe intrinsèque et le facteur domicile feront la différence.'
  },
  {
    league: 'BEL',
    leagueFull: 'Jupiler Pro League',
    home: 'KV Mechelen',
    away: 'KRC Genk',
    bet: 'Les Deux Équipes Marquent (BTTS : OUI)',
    prob: '69%',
    rating: '40/60',
    color: 'badge-warning',
    scenario: 'Genk attaque fort mais défend mal : buts garantis.',
    trap: 'La défense de Genk (36%) est très friable.',
    score: '1-2 ou 1-3',
    logic: 'Genk a une grosse attaque (60%) mais une défense en carton (36%). Mechelen marque à domicile. Le BTTS à 69% est le pari le plus cohérent.'
  },
  {
    league: 'SCO',
    leagueFull: 'Scottish Championship',
    home: 'Airdrie United',
    away: 'St Johnstone',
    bet: 'St Johnstone ou Nul (Double Chance X2)',
    prob: '60%',
    rating: '40/60',
    color: 'badge-value',
    scenario: 'St Johnstone supérieur offensivement, ne doit pas perdre.',
    trap: 'Match fermé et physique (Under 2.5).',
    score: '0-1 ou 1-2',
    logic: 'St Johnstone a une attaque deux fois plus performante (67% vs 33%) et un Global Rating supérieur (+20 pts). Le X2 est très solide face à une équipe d\'Airdrie limitée.'
  },
  {
    league: 'ESP',
    leagueFull: 'LaLiga 2',
    home: 'UD Almeria',
    away: 'FC Andorra',
    bet: 'Almeria ou Nul (1X) & Moins de 3.5 Buts',
    prob: '86%',
    rating: '67/33',
    color: 'badge-safe',
    scenario: 'Almeria domine largement (H2H 86%) face à Andorra.',
    trap: 'Andorra gèle le ballon, risque de match ennuyeux.',
    score: '1-0 ou 2-0',
    logic: 'Almeria est supérieur de 34 points au Global Rating et domine 86% des duels. Andorra (Attaque 36%) est trop inoffensif pour espérer gagner.'
  },
  {
    league: 'GER',
    leagueFull: '2. Bundesliga',
    home: '1. FC Nürnberg',
    away: 'Karlsruher SC',
    bet: 'Karlsruher SC ou Nul (Double Chance X2)',
    prob: '80%',
    rating: '40/61',
    color: 'badge-safe',
    scenario: 'Karlsruhe bête noire de Nuremberg (80% succès).',
    trap: 'Match tactique fermé, peu de buts.',
    score: '0-1 ou 1-1',
    logic: 'Karlsruhe est structurellement supérieur (+21 points) et réussit très bien face à Nuremberg (80% H2H). Le X2 est la base logique.'
  },
  {
    league: 'GER',
    leagueFull: '2. Bundesliga',
    home: 'Fortuna Düsseldorf',
    away: 'Preuẞen Münster',
    bet: 'Victoire de Fortuna Düsseldorf',
    prob: '65%',
    rating: '63/37',
    color: 'badge-value',
    scenario: 'Düsseldorf machine à domicile contre un promu fragile.',
    trap: 'Münster peut marquer (xG 1.02), BTTS possible.',
    score: '2-1 ou 3-1',
    logic: '26 points d\'écart de niveau. Düsseldorf est une machine à domicile (Forme 67%) face à un promu qui voyage mal. La victoire est une value.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 2 BKT',
    home: 'Amiens SC',
    away: 'US Dunkerque',
    bet: 'Dunkerque ou Nul (Double Chance X2)',
    prob: '80%',
    rating: '33/68',
    color: 'badge-safe',
    scenario: 'Dunkerque (Défense 69%) bête noire d\'Amiens.',
    trap: 'Match très fermé, risque de 0-0.',
    score: '0-1 ou 0-0',
    logic: 'Dunkerque a une défense de fer (69%) face à une équipe d\'Amiens en crise (Défense 31%). Avec un Global Rating double (68% vs 33%), Dunkerque ne perdra pas.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 2 BKT',
    home: 'Clermont Foot',
    away: 'Rodez AF',
    bet: 'Rodez ou Nul (Double Chance X2)',
    prob: '75%',
    rating: '50/50',
    color: 'badge-value',
    scenario: 'Rodez en pleine confiance face à Clermont en crise.',
    trap: 'Clermont est la bête noire historique (75%).',
    score: '1-1 ou 0-1',
    logic: 'Rodez est invaincu (Forme 75%) alors que Clermont perd tout (Forme 25%). Malgré l\'historique, la dynamique actuelle protège Rodez de la défaite.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 2 BKT',
    home: 'Pau FC',
    away: 'US Boulogne',
    bet: 'Victoire de Pau',
    prob: '54%',
    rating: '66/34',
    color: 'badge-safe',
    scenario: 'Pau bien supérieur (66%) à domicile.',
    trap: 'Boulogne va défendre bas.',
    score: '2-0 ou 2-1',
    logic: '32 points d\'écart au Global Rating. Pau domine 75% des confrontations et Boulogne a une attaque inoffensive (xG 0.91).'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 2 BKT',
    home: 'Red Star FC 93',
    away: 'AS Nancy Lorraine',
    bet: 'Red Star ou Nul (Double Chance 1X)',
    prob: '85%',
    rating: '64/36',
    color: 'badge-safe',
    scenario: 'Red Star domine Nancy historiquement (85%).',
    trap: 'Match verrouillé, peu de buts attendus.',
    score: '1-0 ou 0-0',
    logic: 'Nancy est friable (Global 36%) et réussit mal face au Red Star (85% de défaites). À domicile, le Red Star assurera l\'essentiel dans un match fermé.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 2 BKT',
    home: 'Stade Lavallois',
    away: 'FC Annecy',
    bet: 'Annecy ou Nul (Double Chance X2)',
    prob: '83%',
    rating: '34/66',
    color: 'badge-safe',
    scenario: 'Laval en crise totale face à un Annecy libéré.',
    trap: 'Risque de match nul si Laval ferme tout.',
    score: '0-1 ou 1-1',
    logic: 'Écart de forme abyssal (17% vs 83%). Annecy est structurellement deux fois plus fort que Laval actuellement. Le X2 est une base solide.'
  },
  {
    league: 'NED',
    leagueFull: 'Eerste Divisie',
    home: 'ADO Den Haag',
    away: 'MVV Maastricht',
    bet: 'ADO Den Haag ou Nul (Double Chance 1X)',
    prob: '93%',
    rating: '60/40',
    color: 'badge-value',
    scenario: 'ADO invincible face à MVV (93% historique).',
    trap: 'Forme actuelle d\'ADO (3 défaites) inquiétante.',
    score: '1-1 ou 2-1',
    logic: 'Malgré la mauvaise forme, l\'historique est implacable (93% de succès pour ADO). Avec un effectif supérieur (60% vs 40%), ADO ne perdra pas.'
  },
  {
    league: 'NED',
    leagueFull: 'Eerste Divisie',
    home: 'Almere City FC',
    away: 'Helmond Sport',
    bet: 'Victoire d\'Almere City',
    prob: '46%',
    rating: '75/25',
    color: 'badge-value',
    scenario: 'Gouffre offensif : Almere (75%) va pilonner Helmond.',
    trap: 'Helmond tentera de tenir le 0-0.',
    score: '2-0 ou 3-0',
    logic: 'Almere possède une attaque notée à 75% contre 25% pour Helmond. Cet écart de 50 points doit se traduire par une victoire à domicile.'
  },
  {
    league: 'NED',
    leagueFull: 'Eerste Divisie',
    home: 'FC Dordrecht',
    away: 'FC Emmen',
    bet: 'Victoire de Dordrecht',
    prob: '64%',
    rating: '71/29',
    color: 'badge-safe',
    scenario: 'Dordrecht en feu (4 victoires) face à une passoire.',
    trap: 'Emmen peut marquer un but (BTTS possible).',
    score: '2-0 ou 3-1',
    logic: 'Dordrecht est invaincu récemment (Forme 77%) tandis qu\'Emmen a une défense catastrophique (29%). Victoire logique à domicile.'
  },
  {
    league: 'NED',
    leagueFull: 'Eerste Divisie',
    home: 'Jong PSV U21',
    away: 'De Graafschap',
    bet: 'Les Deux Équipes Marquent (BTTS : OUI)',
    prob: '69%',
    rating: '65/56',
    color: 'badge-warning',
    scenario: 'Attaques en forme et défenses friables : festival attendu.',
    trap: 'De Graafschap est la bête noire (H2H).',
    score: '1-2 ou 2-2',
    logic: 'Jong PSV attaque fort (65%) mais défend mal. De Graafschap marque à l\'extérieur. Le BTTS à 70% est la stat la plus fiable.'
  },
  {
    league: 'NED',
    leagueFull: 'Eerste Divisie',
    home: 'RKC Waalwijk',
    away: 'Roda JC Kerkrade',
    bet: 'Waalwijk ou Nul (Double Chance 1X)',
    prob: '62%',
    rating: '62/39',
    color: 'badge-safe',
    scenario: 'Waalwijk favori face à un Roda en crise.',
    trap: 'Roda va jouer avec l\'énergie du désespoir.',
    score: '2-1 ou 1-1',
    logic: 'Roda est en crise de confiance (0-3 récent) et Waalwijk domine l\'historique (62%). À domicile, Waalwijk devrait assurer au moins le nul.'
  },
  {
    league: 'DEN',
    leagueFull: 'Superliga',
    home: 'Randers FC',
    away: 'Vejle BK',
    bet: 'Victoire de Randers FC',
    prob: '54%',
    rating: '67/33',
    color: 'badge-safe',
    scenario: 'Randers (Défense 75%) trop solide pour Vejle.',
    trap: 'Vejle a une grosse stat d\'attaque théorique (89%).',
    score: '1-0 ou 2-0',
    logic: 'Randers a une défense de fer (75%) et domine Vejle 93% du temps. L\'écart de forme (88% vs 13%) est sans appel.'
  },
  {
    league: 'CRO',
    leagueFull: 'SuperSport HNL',
    home: 'NK Slaven Belupo',
    away: 'NK Lokomotiva Zagreb',
    bet: 'Victoire du NK Lokomotiva Zagreb',
    prob: '60%',
    rating: '38/62',
    color: 'badge-safe',
    scenario: 'Gouffre de forme : Lokomotiva (83%) doit gagner.',
    trap: 'Match annoncé avec peu de buts.',
    score: '0-1 ou 0-2',
    logic: 'Slaven est en désastre (Forme 17%). La Lokomotiva (Forme 83%, Global 62%) est supérieure et devrait s\'imposer face à une équipe qui ne gagne plus.'
  },
  {
    league: 'POL',
    leagueFull: 'Ekstraklasa',
    home: 'Radomiak Radom',
    away: 'Korona Kielce',
    bet: 'Radomiak ou Nul (Double Chance 1X)',
    prob: '77%',
    rating: '57/43',
    color: 'badge-safe',
    scenario: 'Radomiak solide à domicile et en forme.',
    trap: 'Korona capable de coups d\'éclat à l\'extérieur.',
    score: '1-0 ou 2-1',
    logic: 'Radomiak a fait une grosse préparation et reste solide défensivement. Korona manque de régularité. Le 1X est très sûr.'
  },
  {
    league: 'POL',
    leagueFull: 'Ekstraklasa',
    home: 'GKS Katowice',
    away: 'Legia Varsovie',
    bet: 'GKS Katowice ou Nul (Double Chance 1X)',
    prob: '81%',
    rating: '58/43',
    color: 'badge-value',
    scenario: 'Katowice (4 victoires) reçoit un Legia malade.',
    trap: 'Legia reste le favori théorique des bookmakers.',
    score: '1-0 ou 2-0',
    logic: 'Katowice est sur 4 victoires de suite avec une défense à 67%. Le Legia est en crise (Forme 33%). La dynamique prime sur le nom.'
  },
  {
    league: 'ROU',
    leagueFull: 'Liga I',
    home: 'Petrolul Ploiesti',
    away: 'Arges Pitesti',
    bet: 'Arges Pitesti ou Nul (Double Chance X2)',
    prob: '60%',
    rating: '30/70',
    color: 'badge-safe',
    scenario: 'Arges solide face à une attaque stérile (Petrolul).',
    trap: 'Match fermé, peu de buts (Under 2.5).',
    score: '0-1 ou 0-2',
    logic: 'Petrolul a la pire attaque (30%) et joue à domicile sans marquer. Arges est performant à l\'extérieur et vise les playoffs. Le X2 est la sécurité.'
  }
];