const matches = 
[
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'RCD Espanyol',
    away: 'Celta Vigo',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '60%',
    rating: '54% / 46%',
    color: 'badge-warning',
    scenario: 'Un premier acte prudent marqué par des blocs compacts, suivi d\'une seconde période plus ouverte où les statistiques offensives s\'envolent.',
    trap: 'Paradoxe statistique extrême : L\'Espanyol a une forme désastreuse (17%) mais domine historiquement le Celta avec 80% de réussite récente en H2H.',
    score: '1-1',
    logic: 'Les xG serrés (1.20 vs 1.02) et une probabilité de 68% pour +1.5 buts annoncent un match disputé. Le verdict s\'appuie sur le facteur "Diesel" : les deux équipes inscrivent 70% de leurs buts après la pause.'
  },
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'Getafe',
    away: 'Villarreal',
    bet: 'Double Chance : Nul ou Villarreal (N2)',
    prob: '80%',
    rating: '41% / 59%',
    color: 'badge-safe',
    scenario: 'Villarreal devrait contrôler les débats face à un Getafe prudent et regroupé, cherchant à percer le bloc par la patience pour une victoire à la marge.',
    trap: 'Getafe est expert pour "subir" et arracher des 0-0 à domicile, rendant la victoire sèche dangereuse malgré la supériorité technique adverse.',
    score: '0-1',
    logic: 'Villarreal domine statistiquement (57% attaque, 75% H2H) avec 1.13 xG attendus contre 0.87. Le choix N2 est sécurisé par un historique implacable (Villarreal invaincu lors des 14 dernières confrontations).'
  },
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'Sevilla',
    away: 'Alaves',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '60%',
    rating: '44% / 56%',
    color: 'badge-warning',
    scenario: 'Sevilla devrait dominer la possession initialement, mais le match basculera probablement après la pause face à une équipe d\'Alaves qui a tendance à craquer en fin de rencontre.',
    trap: 'Historique paradoxal : Sevilla est le favori théorique à domicile, mais Alaves est sa "bête noire" avec 71% de réussite en H2H et 3 victoires sur les 5 derniers duels.',
    score: '1-1',
    logic: 'Le modèle prévoit un duel serré (39% de chaque côté) avec 54% de chances que les deux marquent. Le choix se porte sur la seconde période car Alaves y a encaissé 12 de ses 13 derniers buts.'
  },
  {
    league: 'ESP',
    leagueFull: 'La Liga',
    home: 'Real Madrid',
    away: 'Real Sociedad',
    bet: 'Victoire du Real Madrid',
    prob: '73%',
    rating: '76% / 24%',
    color: 'badge-safe',
    scenario: 'Le Real Madrid devrait imposer un pressing haut dès le coup d’envoi pour étouffer la Sociedad, visant un avantage rapide au tableau d’affichage grâce à son efficacité offensive.',
    trap: 'Série d’invincibilité de la Sociedad : les visiteurs n’ont pas perdu depuis 10 matchs, incluant une victoire contre le Barça, ce qui pourrait surprendre un Real trop confiant.',
    score: '3-1',
    logic: 'Le Real Madrid affiche une domination statistique écrasante (2.54 xG, 93% H2H) et reste impérial au Bernabéu. La victoire sèche est validée par l’historique récent de 5 succès consécutifs contre cet adversaire.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'Bayer Leverkusen',
    away: 'FC St. Pauli',
    bet: 'Victoire du Bayer Leverkusen',
    prob: '64%',
    rating: '67% / 33%',
    color: 'badge-safe',
    scenario: 'Leverkusen devrait confisquer le ballon dès l\'entame pour asphyxier le bloc bas de St. Pauli, cherchant à réitérer la domination physique affichée lors de leur récent duel en Coupe.',
    trap: 'Relâchement post-Coupe : La victoire facile 3-0 il y a 10 jours pourrait induire un excès de confiance face à une équipe de St. Pauli capable d\'exploits isolés.',
    score: '2-0',
    logic: 'Le Bayer est impérial à domicile (4V-1N-1D) et bénéficie d\'un ascendant psychologique total avec 93% de réussite en H2H. La solidité défensive locale couplée à la fébrilité de St. Pauli en fin de match (65% de buts encaissés en 2ème MT) sécurise ce pronostic.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'Eintracht Frankfurt',
    away: 'Borussia Mönchengladbach',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '60%',
    rating: '59% / 41%',
    color: 'badge-warning',
    scenario: 'Un match de "crise" où la tension devrait paralyser la première période, avant que les largesses défensives chroniques de Francfort ne libèrent des espaces après la pause.',
    trap: 'L\'historique H2H ultra-dominant de Francfort (85%) est en contradiction totale avec leur forme actuelle catastrophique (9 matchs sans victoire), rendant le pari 1N2 extrêmement risqué.',
    score: '1-1',
    logic: 'Avec 1.58 xG pour Francfort et 1.04 pour Gladbach, le potentiel offensif existe mais la confiance est absente. Le choix s\'oriente sur la 2ème MT car Francfort encaisse systématiquement en fin de match depuis 9 rencontres.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'Hamburger SV',
    away: 'Union Berlin',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '49% / 51%',
    color: 'badge-safe',
    scenario: 'Une première période cadenassée et tactique où les occasions seront rares (moyenne de 0.33 but), laissant place à une seconde mi-temps plus ouverte par la fatigue des blocs.',
    trap: 'Le H2H dominant de l’Union Berlin (71%) est trompeur car il repose sur une forme passée, alors que le club est actuellement incapable de gagner (6 matchs sans succès).',
    score: '1-0',
    logic: 'Hambourg ne remplit pas la règle de victoire à domicile (1V-3N-2D) et l’Union est en crise. Les stats "Diesel" sont décisives : la majorité des buts des deux clubs surviennent après la pause.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: '1899 Hoffenheim',
    away: 'SC Freiburg',
    bet: 'Victoire de Hoffenheim',
    prob: '58%',
    rating: '51% / 50%',
    color: 'badge-safe',
    scenario: 'Hoffenheim devrait étouffer Freiburg par un jeu offensif intense dès l\'entame, profitant de sa forme impériale à domicile (7 victoires consécutives) pour briser le bloc adverse.',
    trap: 'Le statut de "bête noire" de Freiburg : Hoffenheim n\'a remporté qu\'un seul des 13 derniers duels directs, un historique (85% H2H) qui contredit totalement la dynamique actuelle.',
    score: '2-1',
    logic: 'Hoffenheim remplit la règle du domicile avec une série de victoires éclatantes à la PreZero Arena. La fatigue de Freiburg, sortant de 120 minutes en Coupe, valide la victoire sèche malgré le passif historique.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'Werder Bremen',
    away: 'Bayern München',
    bet: 'Double Chance : Nul ou Bayern München (N2)',
    prob: '80%',
    rating: '13% / 87%',
    color: 'badge-safe',
    scenario: 'Une domination bavaoise totale est attendue avec un Werder acculé dans sa moitié de terrain, subissant les assauts répétés de la meilleure attaque du championnat.',
    trap: 'Le piège du "match parfait" : Bien que le Bayern survole les stats (2.92 xG), la règle algorithmique interdit la victoire sèche à l\'extérieur suite à leur récent nul contre Hambourg.',
    score: '0-3',
    logic: 'Le différentiel statistique est abyssal (87% vs 13%). Cependant, l\'application stricte de la "Règle de l\'Extérieur" impose la Double Chance pour sécuriser le pari face à un Werder en crise profonde à domicile.'
  },
  {
    league: 'GER',
    leagueFull: 'Bundesliga',
    home: 'VfB Stuttgart',
    away: '1. FC Köln',
    bet: 'Victoire du VfB Stuttgart',
    prob: '60%',
    rating: '71% / 29%',
    color: 'badge-safe',
    scenario: 'Stuttgart devrait confisquer le ballon et imposer un rythme élevé, exploitant les couloirs pour forcer le verrou d\'une équipe de Cologne en difficulté défensive.',
    trap: 'Le "match de patience" : Cologne pourrait tenter de casser le rythme pour arracher un nul, mais leur incapacité à gagner à l\'extérieur depuis 6 matchs limite leur menace.',
    score: '2-0',
    logic: 'Stuttgart valide la règle du domicile avec 4 victoires sur les 6 derniers matchs. La domination en H2H (93%) et la crise de résultats de Cologne hors de ses bases confirment la victoire sèche des locaux.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Como',
    away: 'Fiorentina',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '71% / 29%',
    color: 'badge-safe',
    scenario: 'Côme devrait dominer territorialement face à une Viola en crise, mais le score aura tendance à basculer après la pause, moment où Côme accélère (1.61 but/match en moyenne).',
    trap: 'L\'excès de confiance de Côme : malgré une supériorité statistique (61% de probabilité), ils ne remplissent pas la règle des 4 victoires à domicile (3V-2N-1D), rendant le pari sec risqué.',
    score: '2-1',
    logic: 'Côme est en pleine forme (4-1-0) contre une Fiorentina relégable (18ème). Le filtre "Diesel" est privilégié car les deux clubs affichent une fréquence de buts tardifs très élevée (BTTS fréquent en fin de match).'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Lazio',
    away: 'Atalanta',
    bet: 'Double Chance : Nul ou Atalanta (N2)',
    prob: '80%',
    rating: '49% / 51%',
    color: 'badge-safe',
    scenario: 'Un choc tactique fermé où l\'Atalanta devrait progressivement prendre l\'ascendant physique sur une Lazio privée de Romagnoli, cherchant la faille en seconde période.',
    trap: 'L\'historique H2H favorable à la Lazio (62%) masque une réalité actuelle inversée : l\'Atalanta est invaincue depuis 7 matchs de championnat tandis que la Lazio peine à domicile.',
    score: '1-1',
    logic: 'L\'Atalanta est supérieure sur la forme (56% vs 44%) et l\'attaque (1.33 xG). La règle de l\'extérieur impose cependant le N2 car la Dea a concédé deux nuls lors de ses 6 dernières sorties.'
  },
  {
    league: 'ITA',
    leagueFull: 'Serie A',
    home: 'Inter Milan',
    away: 'Juventus',
    bet: 'Victoire de l\'Inter Milan',
    prob: '51%',
    rating: '54% / 46%',
    color: 'badge-warning',
    scenario: 'Le leader devrait imposer son rythme dès l\'entame pour exploiter la fébrilité actuelle d\'une Juventus privée de Vlahovic et en difficulté défensive.',
    trap: 'Le spectre du "Derby d\'Italie" : l\'historique H2H (62% pour la Juve) et les récents scores fleuves (4-4, 4-3) rappellent que ce match échappe souvent à la logique pure.',
    score: '2-1',
    logic: 'L\'Inter remplit parfaitement la règle du domicile avec 5 victoires sur les 6 derniers matchs. La méforme de la Juventus (2 nuls, 2 défaites) et ses 5 buts encaissés récemment valident le succès des Nerazzurri.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'Olympique de Marseille',
    away: 'RC Strasbourg',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '55% / 45%',
    color: 'badge-safe',
    scenario: 'Une entame de match où Strasbourg tentera de contenir les assauts olympiens, avant que la rencontre ne se débrime en fin de match, période où les deux équipes sont les plus prolifiques.',
    trap: 'Le paradoxe du Vélodrome : Marseille est invaincu contre Strasbourg depuis 20 réceptions, mais le nombre élevé de nuls historiques (9/20) rend la victoire sèche risquée.',
    score: '2-1',
    logic: 'L\'OM ne valide pas la règle des 4 victoires à domicile (3V-1N-2D). Le filtre "Diesel" est prioritaire car Strasbourg marque 75% de ses buts après la 75ème minute.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'LOSC Lille',
    away: 'Stade Brestois 29',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '60%',
    rating: '58% / 42%',
    color: 'badge-warning',
    scenario: 'Lille devrait buter sur un bloc brestois compact en début de match, avant que la fatigue n\'ouvre des espaces en seconde période, secteur où Brest a déjà concédé 12 buts cette saison.',
    trap: 'La méforme historique du LOSC : n\'ayant pas gagné en L1 en 2026, leur statut de favori théorique (60%) est fragile face à des Brestois en pleine reprise.',
    score: '1-1',
    logic: 'Lille échoue à la règle du domicile (1 victoire sur 6). Les statistiques de début de match de Brest (record de buts encaissés en 1ère MT) forcent souvent des scénarios de réaction après la pause.'
  },
  {
    league: 'FRA',
    leagueFull: 'Ligue 1',
    home: 'Paris FC',
    away: 'RC Lens',
    bet: 'Double Chance : Nul ou Lens (N2)',
    prob: '80%',
    rating: '35% / 65%',
    color: 'badge-safe',
    scenario: 'Le dauphin lensois devrait confisquer le ballon face à un PFC regroupé, cherchant à forcer le verrou parisien par une supériorité technique évidente.',
    trap: 'La spécialité du Paris FC : "Roi du match nul" à domicile (3 nuls consécutifs), ils ont la capacité de frustrer les cadors comme ils l\'ont fait contre Marseille (2-2).',
    score: '0-2',
    logic: 'Lens est l\'immense favori (10 victoires sur 11 matchs), mais la règle de l\'extérieur impose la Double Chance en raison de leur récent revers à Marseille. Le N2 sécurise face à la résilience parisienne.'
  },
  {
    league: 'TUR',
    leagueFull: 'Süper Lig',
    home: 'Gençlerbirliği',
    away: 'Çaykur Rizespor',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '60%',
    rating: '47% / 53%',
    color: 'badge-warning',
    scenario: 'Une entame de match verrouillée où Gençlerbirliği butera sur un bloc compact, avant que les lacunes défensives des deux camps (31 buts encaissés chacun) ne créent des ouvertures après la pause.',
    trap: 'Le mirage de la forme : Gençlerbirliği est présenté comme "en grande forme" par l\'IA mais n\'a gagné qu\'un match sur cinq en ligue, face à un Rizespor qui reste leur bête noire (3 victoires consécutives).',
    score: '1-1',
    logic: 'L\'équipe à domicile échoue à la règle des 4 victoires (2V-2N-2D). Le filtre "Diesel" s\'impose car Rizespor, poussé par l\'urgence de sa crise de résultats, a tendance à débrider ses matchs en seconde période.'
  },
  {
    league: 'TUR',
    leagueFull: 'Süper Lig',
    home: 'Alanyaspor',
    away: 'Konyaspor',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '37% / 63%',
    color: 'badge-safe',
    scenario: 'Un duel de milieu de tableau qui devrait s\'animer tardivement, suivant la tendance de Konyaspor dont 5 des 6 derniers matchs ont basculé après la pause.',
    trap: 'L\'instabilité chronique d\'Alanyaspor à domicile (1V-2N-3D) contredit son statut de favori historique (93% H2H), rendant le pari sur le vainqueur trop risqué.',
    score: '1-1',
    logic: 'Alanyaspor ne remplit pas la règle de victoire à domicile. La sécurité maximale repose sur les statistiques de fin de match, les deux équipes se livrant davantage en seconde période selon les derniers rapports H2H.'
  },
  {
    league: 'TUR',
    leagueFull: 'Süper Lig',
    home: 'Trabzonspor',
    away: 'Fenerbahçe',
    bet: 'Double Chance : Nul ou Fenerbahçe (N2)',
    prob: '80%',
    rating: '39% / 61%',
    color: 'badge-safe',
    scenario: 'Fenerbahçe devrait contrôler le tempo, mais se heurtera à une équipe de Trabzonspor très solide au Papara Park (4 victoires sur 6), menant à un affrontement serré.',
    trap: 'La tentation du 2 sec : Fenerbahçe domine le H2H (80%) et est invaincu, mais la règle de l\'extérieur interdit la victoire sèche suite à leurs deux nuls lors des six dernières sorties.',
    score: '1-2',
    logic: 'Fenerbahçe affiche une supériorité offensive et défensive (59%). Cependant, la forme domestique de Trabzonspor (4V-1N-1D) impose la sécurité du N2 pour couvrir un éventuel partage des points.'
  },
  {
    league: 'SAU',
    leagueFull: 'Pro League',
    home: 'Al Riyadh',
    away: 'Al Khaleej',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '46% / 54%',
    color: 'badge-safe',
    scenario: 'Un match de bas de tableau marqué par une peur de perdre initiale, qui devrait se débloquer en fin de rencontre suite à la fatigue défensive d\'Al Riyadh.',
    trap: 'La statistique de "défense solide" de l\'IA pour Al Riyadh est trompeuse : le club a encaissé au moins un but lors de ses 15 derniers matchs officiels.',
    score: '0-1',
    logic: 'Al Riyadh est en crise totale (15 matchs sans victoire). Le filtre "Diesel" est validé par l\'incapacité des deux équipes à marquer tôt et par la tendance d\'Al Khaleej à scorer en fin de match (26% après la 76e).'
  },
  {
    league: 'SAU',
    leagueFull: 'Pro League',
    home: 'Al Najma',
    away: 'Al Kholood',
    bet: 'Double Chance : Nul ou Al Kholood (N2)',
    prob: '80%',
    rating: '30% / 70%',
    color: 'badge-safe',
    scenario: 'Al Kholood devrait dominer territorialement face à la lanterne rouge, mais pourrait concéder des temps forts en fin de match, sécurisant le résultat par un nul ou une victoire courte.',
    trap: 'Le piège de la lanterne rouge : Al Najma n\'a gagné aucun de ses 20 matchs, mais Al Kholood (14ème) reste une équipe fragile à l\'extérieur, rendant le "1N2" sec périlleux.',
    score: '1-2',
    logic: 'Al Najma est en crise totale (0 victoire). Al Kholood a l\'avantage H2H (victoires 5-1 et 1-0) mais la règle de l\'extérieur impose la Double Chance suite à leur nul récent contre Damac.'
  },
  {
    league: 'SAU',
    leagueFull: 'Pro League',
    home: 'Al-Fateh',
    away: 'Al-Nassr',
    bet: 'Victoire de Al-Nassr',
    prob: '66%',
    rating: '22% / 78%',
    color: 'badge-safe',
    scenario: 'Al-Nassr devrait imposer une domination totale dès l\'entame, profitant de sa forme étincelante (6 victoires de suite) pour plier le match rapidement face à une défense aux abois.',
    trap: 'Le relâchement post-ouverture : Al-Nassr marque beaucoup mais Al-Fateh reste dangereux à domicile sur des contres, bien que l\'écart de niveau semble trop grand pour une surprise.',
    score: '1-3',
    logic: 'Al-Nassr valide la condition de "domination absolue" avec 6 victoires consécutives et une attaque de feu. Face à un Al-Fateh qui ne gagne plus (0/6), la victoire sèche est validée.'
  },
  {
    league: 'POR',
    leagueFull: 'Primeira Liga',
    home: 'Casa Pia',
    away: 'Arouca',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '37% / 63%',
    color: 'badge-safe',
    scenario: 'Une première période tactique et fermée où Casa Pia tentera de frustrer Arouca, avant que les visiteurs ne trouvent la faille après la pause, moment où ils marquent le plus.',
    trap: 'La "Bête Noire" : Arouca est en meilleure forme, mais Casa Pia est invaincu lors des 5 derniers duels (4V-1N), créant un paradoxe total entre la forme actuelle et l\'histoire.',
    score: '1-1',
    logic: 'Casa Pia ne gagne pas assez à domicile (1/6) pour être favori. Le choix se porte sur la 2ème mi-temps car Arouca a l\'habitude de réagir tardivement et Casa Pia marque aussi après le repos.'
  },
  {
    league: 'POR',
    leagueFull: 'Primeira Liga',
    home: 'Vitoria Guimarães',
    away: 'Estrela da Amadora',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '58% / 42%',
    color: 'badge-safe',
    scenario: 'Guimarães devrait contrôler le ballon mais buter sur le bloc bas d\'Estrela initialement, avant de faire la différence physiquement en fin de rencontre.',
    trap: 'L\'incapacité de Guimarães à enchaîner à domicile (2 victoires sur 6) rend leur cote de favori (42%) fragile malgré leur historique H2H impeccable.',
    score: '2-0',
    logic: 'Le filtre "Diesel" est décisif : Estrela encaisse 68% de ses buts à l\'extérieur en seconde période, et Guimarães a marqué 8 de ses 10 derniers buts après la 45ème minute.'
  },
  {
    league: 'POR',
    leagueFull: 'Primeira Liga',
    home: 'Gil Vicente',
    away: 'SC Braga',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '39% / 61%',
    color: 'badge-safe',
    scenario: 'Un derby du Minho serré où Braga poussera fort, mais Gil Vicente résistera longtemps avant que le match ne s\'ouvre par fatigue ou prise de risque en seconde période.',
    trap: 'La forteresse de Barcelos : Gil Vicente est capable d\'exploits à domicile (3V-2N-1D) et a déjà battu Braga à l\'aller, ce qui nuance la supériorité théorique des visiteurs.',
    score: '1-2',
    logic: 'Aucune équipe ne remplit les critères de victoire sèche "sûre". La stat clé est que Gil Vicente inscrit 70% de ses buts en 2ème MT, s\'alignant avec la puissance offensive tardive de Braga.'
  },
  {
    league: 'BEL',
    leagueFull: 'Jupiler Pro League',
    home: 'OH Leuven',
    away: 'Dender',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '60%',
    rating: '50% / 50%',
    color: 'badge-warning',
    scenario: 'Un duel de bas de tableau crispé par la peur de perdre, qui devrait se décanter tardivement face aux erreurs défensives chroniques de Dender en fin de match.',
    trap: 'L\'illusion offensive : OHL est donné à 50% favori mais n\'a gagné qu\'une fois sur 6 à domicile, rendant le pari sur le vainqueur très aléatoire.',
    score: '1-1',
    logic: 'Dender encaisse plus de 60% de ses buts en 2ème période. OHL étant incapable de tuer les matchs à domicile, le pari sur les buts tardifs est la meilleure option statistique.'
  },
  {
    league: 'BEL',
    leagueFull: 'Jupiler Pro League',
    home: 'Charleroi',
    away: 'Gent',
    bet: 'Double Chance : Nul ou Gent (N2)',
    prob: '80%',
    rating: '48% / 52%',
    color: 'badge-safe',
    scenario: 'Gent devrait contrôler le jeu face à un Charleroi en difficulté à domicile, cherchant à assurer au minimum le nul pour la course aux playoffs.',
    trap: 'L\'irrégularité de Gent : capable de gagner nettement comme de concéder des nuls contre des "petits", ce qui interdit la victoire sèche à l\'extérieur.',
    score: '1-2',
    logic: 'La règle de l\'extérieur s\'applique : Gent est supérieur (H2H favorable, meilleure forme) mais a fait trop de nuls récents. Le N2 couvre la fragilité de Charleroi au Mambourg.'
  },
  {
    league: 'BEL',
    leagueFull: 'Jupiler Pro League',
    home: 'Standard de Liège',
    away: 'Union St. Gilloise',
    bet: 'Double Chance : Nul ou Union St. Gilloise (N2)',
    prob: '80%',
    rating: '20% / 80%',
    color: 'badge-safe',
    scenario: 'L\'Union devrait dominer dans le jeu mais se heurter à un bloc liégeois regroupé, avant de faire la différence ou d\'assurer le nul en fin de match.',
    trap: 'Règle de l\'Extérieur : L\'Union est largement supérieure (leader) mais a concédé 2 nuls lors de ses 6 derniers déplacements, interdisant la victoire sèche par sécurité.',
    score: '0-2',
    logic: 'Le Standard est en difficulté à domicile (2V-0N-4D) face à une Union invaincue depuis 8 matchs. Le N2 couvre les éventuels accrocs à l\'extérieur du leader.'
  },
  {
    league: 'SCO',
    leagueFull: 'Premiership',
    home: 'Falkirk',
    away: 'Dundee United',
    bet: 'Victoire de Falkirk',
    prob: '65%',
    rating: '30% / 70%',
    color: 'badge-safe',
    scenario: 'Falkirk devrait profiter de sa dynamique à domicile pour enfoncer une équipe de Dundee United en crise, ouvrant le score avant la pause.',
    trap: 'Aucun piège majeur détecté, si ce n\'est un sursaut d\'orgueil improbable de Dundee après 4 défaites consécutives.',
    score: '2-0',
    logic: 'Falkirk valide la "Règle du Domicile" avec 4 victoires sur les 6 derniers matchs. Dundee United est en chute libre (4 défaites de rang) et a déjà perdu 3-0 contre Falkirk cette saison.'
  },
  {
    league: 'SCO',
    leagueFull: 'Premiership',
    home: 'Dundee FC',
    away: 'Livingston',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '33% / 68%',
    color: 'badge-safe',
    scenario: 'Un match qui débutera sur un faux rythme avant que la défense de Livingston, privée de son capitaine, ne s\'effondre physiquement dans les 20 dernières minutes.',
    trap: 'L\'irrégularité de Dundee : favoris (52%), ils ne comptent que 3 victoires sur 6 à domicile, ce qui rend le pari sur le vainqueur plus risqué que le marché des buts.',
    score: '2-1',
    logic: 'Livingston est une épave à l\'extérieur (25 matchs sans victoire). Le choix se porte sur la 2ème MT car Dundee ne gagne pas assez souvent pour être "Safe", et Livingston encaisse 28% de ses buts en fin de match.'
  },
  {
    league: 'SCO',
    leagueFull: 'Premiership',
    home: 'Hibernian',
    away: 'St Mirren',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '52% / 48%',
    color: 'badge-safe',
    scenario: 'Une bataille physique au milieu de terrain qui devrait se décanter tardivement, Hibernian accélérant souvent après l\'heure de jeu à Easter Road.',
    trap: 'Le paradoxe des stats : Hibernian est donné perdant par l\'IA (24%) alors qu\'ils sont solides à domicile (3V-2N-1D) contre un St Mirren catastrophique à l\'extérieur.',
    score: '2-1',
    logic: 'Hibernian échoue de peu à la règle du domicile (3V). Le filtre "Diesel" est la meilleure option : St Mirren s\'effondre régulièrement en fin de match (ex: défaite 4-3 récente).'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'Heracles Almelo',
    away: 'NAC Breda',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '60%',
    rating: '44% / 56%',
    color: 'badge-warning',
    scenario: 'La peur de perdre ce duel de bas de tableau devrait verrouiller le premier acte, avant que les pires défenses du championnat ne craquent sous la fatigue.',
    trap: 'Tension du maintien : Ce genre de match "à six points" produit souvent des premières mi-temps très fermées et tactiques.',
    score: '1-1',
    logic: 'Heracles ne gagne presque plus à domicile (1/6). Avec deux défenses passoires (57 buts encaissés pour Heracles), le match finira par s\'ouvrir, statistiquement en seconde période (65% des buts).'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'Excelsior',
    away: 'AZ Alkmaar',
    bet: 'Double Chance : Nul ou AZ Alkmaar (N2)',
    prob: '80%',
    rating: '62% / 38%',
    color: 'badge-safe',
    scenario: 'AZ Alkmaar va monopoliser le ballon face à un bloc bas, assurant au minimum le point du nul grâce à sa supériorité technique.',
    trap: 'L\'inefficacité relative de l\'AZ : malgré leur invincibilité, ils ont concédé des nuls 0-0 contre des équipes faibles (Almere), rendant la victoire sèche incertaine.',
    score: '0-2',
    logic: 'L\'AZ est invaincu à l\'extérieur récemment (4V-2N). La règle de l\'extérieur impose le N2 par sécurité suite à leurs deux nuls récents, mais Excelsior (2V sur 6 à domicile) ne semble pas en mesure de gagner.'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'Ajax Amsterdam',
    away: 'Fortuna Sittard',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '20% / 80%',
    color: 'badge-safe',
    scenario: 'L\'Ajax devrait user son adversaire par la possession avant de faire la différence grâce à la profondeur de son banc en seconde période.',
    trap: 'La reconstruction de l\'Ajax : encore en rodage, l\'équipe alterne le très bon et le médiocre au sein d\'un même match, rendant les débuts de rencontres parfois poussifs.',
    score: '3-1',
    logic: 'Ajax ne valide pas la règle impériale à domicile (3V-2N-1D). Le filtre "Diesel" est pertinent car le Fortuna encaisse 1.33 but/match et l\'Ajax marque beaucoup en fin de partie.'
  },
  {
    league: 'NED',
    leagueFull: 'Eredivisie',
    home: 'FC Groningen',
    away: 'FC Utrecht',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '60% / 40%',
    color: 'badge-safe',
    scenario: 'Groningen va tenter de verrouiller le match à l\'Euroborg, mais Utrecht devrait trouver la faille physiquement dans les 30 dernières minutes.',
    trap: 'La "Groningen Special" : Roi du match nul à domicile (3 récents), ils ont la capacité d\'endormir le match jusqu\'au bout (0-0 possible).',
    score: '0-1',
    logic: 'Groningen ne gagne pas (1V sur 6). Utrecht est solide mais c\'est surtout leur stat de buts tardifs (62% après la 60ème minute) qui oriente le pari vers la 2ème mi-temps.'
  },
  {
    league: 'NED',
    leagueFull: 'Eerste Divisie',
    home: 'Vitesse Arnhem',
    away: 'VVV Venlo',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '41% / 59%',
    color: 'badge-safe',
    scenario: 'Vitesse dominera stérilement en début de match avant que la défense de Venlo, catastrophique à l\'extérieur, ne cède logiquement après la pause.',
    trap: 'Le manque de réalisme de Vitesse : solide dans le jeu mais peine à tuer les matchs tôt (nuls 1-1 et 0-0 récents).',
    score: '2-0',
    logic: 'Venlo encaisse 72% de ses buts à l\'extérieur en seconde période. Vitesse, bien que favori, manque de constance pour le pari sec, rendant le pari sur les buts tardifs plus fiable.'
  },
  {
    league: 'SUI',
    leagueFull: 'Super League',
    home: 'FC Zurich',
    away: 'FC Luzern',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '50% / 50%',
    color: 'badge-safe',
    scenario: 'Un derby tactique où les deux équipes s\'observeront avant que Zurich n\'accélère, profitant des baisses de régime chroniques de Lucerne en fin de match.',
    trap: 'L\'épidémie de nuls : 4 matchs nuls sur les 6 derniers H2H, rendant tout pari sur le résultat final (1N2) extrêmement hasardeux.',
    score: '1-1',
    logic: 'Zurich marque 64% de ses buts à domicile en 2ème MT. Lucerne encaisse beaucoup dans le dernier quart d\'heure. Le scénario "Diesel" est écrit d\'avance.'
  },
  {
    league: 'SUI',
    leagueFull: 'Super League',
    home: 'FC Saint-Gall',
    away: 'Grasshoppers',
    bet: 'Victoire du FC Saint-Gall',
    prob: '70%',
    rating: '37% / 63%',
    color: 'badge-safe',
    scenario: 'Saint-Gall devrait étouffer les Grasshoppers dès le début grâce à l\'intensité mise au Kybunpark, menant à une victoire maîtrisée.',
    trap: 'Aucun piège statistique majeur : Saint-Gall est une forteresse (5V/6) et Grasshoppers ne voyage pas.',
    score: '2-0',
    logic: 'Application parfaite de la "Règle du Domicile" : Saint-Gall a remporté 5 de ses 6 derniers matchs chez lui. Grasshoppers est en perdition à l\'extérieur et dominé historiquement.'
  },
  {
    league: 'SUI',
    leagueFull: 'Super League',
    home: 'BSC Young Boys',
    away: 'FC Winterthur',
    bet: 'Victoire de Young Boys',
    prob: '80%',
    rating: '64% / 36%',
    color: 'badge-safe',
    scenario: 'Une domination bernoise totale est attendue au Wankdorf, Young Boys devant profiter de sa pelouse synthétique pour étouffer la pire défense du championnat à l\'extérieur.',
    trap: 'Aucun piège majeur : Young Boys a remporté 6 des 6 derniers duels et Winterthur reste sur 5 défaites en 6 déplacements, rendant la surprise hautement improbable.',
    score: '3-1',
    logic: 'Application stricte de la "Règle du Domicile" : Young Boys (4V/6 à domicile) affronte une équipe en perdition (1V/6 à l\'extérieur). L\'historique H2H (100% de victoires récentes pour YB) sécurise le pari.'
  },
  {
    league: 'DEN',
    leagueFull: 'Superliga',
    home: 'FC Copenhague',
    away: 'FC Nordsjaelland',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '14% / 86%',
    color: 'badge-safe',
    scenario: 'Une reprise post-trêve tactique où Copenhague, sous pression, jouera la prudence avant de lâcher les chevaux physiquement face à une équipe qui craque souvent en fin de match.',
    trap: 'La forme de Nordsjaelland : donnés favoris par les stats pures (49% vs 29%), ils sont capables de gagner au Parken (comme à l\'aller), rendant le pari sur le vainqueur trop aléatoire.',
    score: '2-2',
    logic: 'Copenhague ne remplit pas la condition de victoire à domicile (3V/6). La stat clé est la fragilité tardive de Nordsjaelland (31% de buts encaissés dans les 20 dernières minutes).'
  },
  {
    league: 'CZE',
    leagueFull: 'Czech Liga',
    home: 'Dukla Praha',
    away: 'FC Zlin',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '22% / 78%',
    color: 'badge-safe',
    scenario: 'Un "match de la peur" pour le maintien qui devrait être verrouillé en première période, avant que la fatigue de Dukla et l\'efficacité tardive de Zlin ne débloquent le tableau d\'affichage.',
    trap: 'Le piège du bas de tableau : Zlin est techniquement supérieur (78% attaque) mais reste une équipe fragile à l\'extérieur, capable de gâcher des occasions et de laisser filer le match.',
    score: '1-2',
    logic: 'Dukla ne gagne pas chez lui (1/6). Zlin inscrit 68% de ses buts à l\'extérieur après la mi-temps, ce qui coïncide parfaitement avec les effondrements physiques de Dukla dans le dernier quart d\'heure.'
  },
  {
    league: 'CZE',
    leagueFull: 'Czech Liga',
    home: 'MFK Karviná',
    away: 'Slavia Prague',
    bet: 'Victoire du Slavia Prague',
    prob: '67%',
    rating: '20% / 80%',
    color: 'badge-safe',
    scenario: 'Une domination praguoise sans partage est attendue. Le Slavia devrait étouffer Karviná d\'entrée pour sécuriser les trois points dans sa course au titre.',
    trap: 'Le relâchement post-européen : si le Slavia a joué en Europe en semaine, une rotation pourrait réduire l\'écart, mais leur profondeur de banc reste largement supérieure.',
    score: '0-3',
    logic: 'Le Slavia valide la condition de "Domination Absolue" : invaincu à l\'extérieur (5V-1N) face à une équipe de bas de tableau qui ne gagne pas chez elle (1V/6). H2H à sens unique (6 victoires de suite).'
  },
  {
    league: 'CZE',
    leagueFull: 'Czech Liga',
    home: '1. FC Slovácko',
    away: 'Bohemians 1905',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '44% / 56%',
    color: 'badge-safe',
    scenario: 'Un match de reprise typique où les deux équipes s\'observeront tactiquement avant que les erreurs individuelles de Bohemians ne coûtent cher en fin de match.',
    trap: 'L\'incertitude de la reprise : après la trêve hivernale, le rythme peut être lent, favorisant un nul vierge à la mi-temps.',
    score: '2-0',
    logic: 'Slovácko ne gagne pas assez à domicile (2/6) pour être un "Safe Bet". Bohemians encaisse 65% de ses buts à l\'extérieur après la 50ème minute, validant la stratégie "Diesel".'
  },
  {
    league: 'CZE',
    leagueFull: 'Czech Liga',
    home: 'Sigma Olomouc',
    away: 'Viktoria Plzeň',
    bet: 'Double Chance : Nul ou Viktoria Plzeň (N2)',
    prob: '80%',
    rating: '26% / 74%',
    color: 'badge-safe',
    scenario: 'Plzeň devrait contrôler le ballon mais se heurter à un bloc bas d\'Olomouc, avant de faire la différence ou d\'assurer le point du nul.',
    trap: 'La forteresse d\'Olomouc : bien que moins forts sur le papier, ils sont capables d\'accrocher les gros à domicile (ex: victoire contre Teplice).',
    score: '1-2',
    logic: 'Plzeň est supérieur (4V/6 à l\'extérieur) mais a concédé un nul récemment, activant la sécurité N2. Olomouc est trop irrégulier pour espérer mieux qu\'un point.'
  },
  {
    league: 'AUT',
    leagueFull: 'Bundesliga',
    home: 'SV Ried',
    away: 'LASK Linz',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '47% / 53%',
    color: 'badge-safe',
    scenario: 'Un derby intense et haché en première période, qui devrait s\'ouvrir physiquement en seconde mi-temps grâce à la profondeur de banc du LASK.',
    trap: 'L\'effet Derby : l\'engagement physique excessif peut bloquer le jeu et mener à un score vierge à la pause, rendant le pari sur les buts en 1ère MT très risqué.',
    score: '1-2',
    logic: 'Ried ne gagne pas à domicile (1/6). LASK marque 65% de ses buts à l\'extérieur après l\'heure de jeu. Tout pointe vers une décision tardive.'
  },
  {
    league: 'AUT',
    leagueFull: 'Bundesliga',
    home: 'TSV Hartberg',
    away: 'SCR Altach',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '42% / 58%',
    color: 'badge-safe',
    scenario: 'Hartberg butera sur le mur défensif d\'Altach initialement, avant de trouver la faille grâce à son meilleur buteur en fin de rencontre.',
    trap: 'La solidité d\'Altach : meilleure défense de 1ère mi-temps, ils peuvent frustrer Hartberg longtemps (0-0 possible à la pause).',
    score: '2-0',
    logic: 'Hartberg échoue de peu à la règle du domicile (3V/6). Altach est solide derrière au début mais craque à la fin. Hartberg marque 65% de ses buts après la pause.'
  },
  {
    league: 'AUT',
    leagueFull: 'Bundesliga',
    home: 'WSG Tirol',
    away: 'Sturm Graz',
    bet: 'Double Chance : Nul ou Sturm Graz (N2)',
    prob: '80%',
    rating: '37% / 64%',
    color: 'badge-safe',
    scenario: 'Le leader Sturm Graz devrait dominer la possession mais pourrait buter sur une équipe tyrolienne regroupée, avant de faire la différence ou d\'assurer le point du nul.',
    trap: 'Le "Nul à l\'extérieur" : Sturm Graz est largement supérieur (44% vs 34%) mais a concédé deux nuls lors de ses 6 derniers déplacements, rendant la victoire sèche risquée.',
    score: '0-2',
    logic: 'Application de la règle de l\'extérieur : Sturm est invaincu lors de ses 6 derniers déplacements (4V-2N) et domine le H2H (4 victoires de suite). Le N2 couvre les accrocs potentiels.'
  },
  {
    league: 'GRE',
    leagueFull: 'Super League 1',
    home: 'Panetolikos',
    away: 'Asteras Tripolis',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '47% / 54%',
    color: 'badge-safe',
    scenario: 'Une première période tactique et fermée typique du championnat grec, suivie d\'une ouverture des espaces lorsque la fatigue s\'installera après l\'heure de jeu.',
    trap: 'L\'inefficacité de Panetolikos : favoris à domicile (40%), ils n\'ont pourtant gagné qu\'un seul de leurs 6 derniers matchs sur leurs terres.',
    score: '1-1',
    logic: 'Le filtre "Diesel" est activé : Panetolikos ne gagne pas assez à domicile. La statistique clé est que plus de 60% des buts de ces deux équipes sont inscrits après la 60ème minute.'
  },
  {
    league: 'GRE',
    leagueFull: 'Super League 1',
    home: 'Levadiakos',
    away: 'Olympiakos',
    bet: 'Double Chance : Nul ou Olympiakos (N2)',
    prob: '80%',
    rating: '30% / 70%',
    color: 'badge-safe',
    scenario: 'Olympiakos va imposer son rythme face à un promu en difficulté, mais devra se méfier d\'un bloc bas capable de tenir le score vierge longtemps.',
    trap: 'Le match piège du favori : Olympiakos domine totalement l\'historique (14 victoires sur 15), mais un nul récent à l\'extérieur (0-0) incite à la prudence via le N2.',
    score: '0-2',
    logic: 'Disparité totale de niveau : Levadiakos (1V sur 6 à domicile) face au 2ème du championnat. La règle de l\'extérieur impose le N2 pour sécuriser le pari à 100%.'
  },
  {
    league: 'GRE',
    leagueFull: 'Super League 1',
    home: 'Volos NFC',
    away: 'Aris Salonique',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '20% / 80%',
    color: 'badge-safe',
    scenario: 'Aris Salonique devrait gérer son effort face à une équipe de Volos en crise, avant d\'accélérer pour faire la décision dans les 30 dernières minutes.',
    trap: 'La stérilité de Volos : avec 5 défaites de rang, ils pourraient fermer le jeu à outrance pour stopper l\'hémorragie, retardant le premier but.',
    score: '0-1',
    logic: 'Volos est en crise (0 victoires). Aris est un spécialiste des fins de match (70% de buts après la 60e minute à l\'extérieur), ce qui valide le scénario d\'une seconde mi-temps plus prolifique.'
  },
  {
    league: 'CRO',
    leagueFull: 'HNL',
    home: 'Dinamo Zagreb',
    away: 'Istra 1961',
    bet: 'Victoire du Dinamo Zagreb',
    prob: '77%',
    rating: '35% / 65%',
    color: 'badge-safe',
    scenario: 'Le Dinamo devrait plier l\'affaire rapidement au Maksimir, profitant de sa forme étincelante pour écraser une équipe d\'Istra inoffensive à l\'extérieur.',
    trap: 'Aucun piège majeur identifié : Dinamo a gagné 5 de ses 6 derniers matchs à domicile et les 7 derniers H2H contre Istra.',
    score: '3-0',
    logic: 'Le "Banker" du week-end. Dinamo remplit toutes les conditions : forteresse à domicile (5V/6), attaque de feu (79% supériorité) et adversaire faible à l\'extérieur.'
  },
  {
    league: 'CRO',
    leagueFull: 'HNL',
    home: 'HNK Rijeka',
    away: 'NK Varazdin',
    bet: 'Victoire de Rijeka',
    prob: '80%',
    rating: '60% / 40%',
    color: 'badge-safe',
    scenario: 'Rijeka devrait assiéger le but de Varazdin dès le début, fort de sa série de 5 victoires consécutives à domicile, pour une victoire maîtrisée.',
    trap: 'La contradiction statistique : les données brutes (Input A) donnent Varazdin favori sur la forme récente, mais la réalité du domicile (Input B : 5V-1N-0D pour Rijeka) est bien plus fiable.',
    score: '2-0',
    logic: 'Rijeka est une machine à domicile (5 victoires de suite, 2 buts encaissés). Varazdin voyage mal (1 victoire sur 6). La règle du domicile est validée sans hésitation.'
  },
  {
    league: 'POL',
    leagueFull: 'Ekstraklasa',
    home: 'Cracovia Krakow',
    away: 'Jagiellonia Białystok',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '52% / 48%',
    color: 'badge-safe',
    scenario: 'Un choc où Cracovia tentera d\'endormir le leader en première période, avant que l\'attaque de feu de Jagiellonia ne se déchaîne dans le dernier quart d\'heure.',
    trap: 'Le feu d\'artifice historique : les duels H2H sont très prolifiques (5.4 buts/match), mais Cracovia a tendance à être très solide en 1ère MT à domicile cette saison.',
    score: '1-2',
    logic: 'Jagiellonia est l\'équipe "Diesel" par excellence (11 buts après la 75ème minute). Cracovia ne gagne pas assez à domicile pour un pari sec, rendant le pari sur la 2ème mi-temps très pertinent.'
  },
  {
    league: 'POL',
    leagueFull: 'Ekstraklasa',
    home: 'Zagłębie Lubin',
    away: 'Raków Częstochowa',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '45% / 55%',
    color: 'badge-safe',
    scenario: 'Une première période bloquée par l\'enjeu du podium, suivie d\'une ouverture des espaces quand Raków fatiguera et que Zagłębie poussera dans le dernier quart d\'heure.',
    trap: 'Le piège du domicile : Zagłębie est fort chez lui (2.2 buts/match) mais Raków est une équipe qui voyage bien, rendant l\'issue du 1N2 trop incertaine (31% vs 46%).',
    score: '1-1',
    logic: 'Zagłębie ne valide pas la règle des 4 victoires à domicile (3V). La statistique clé est que Raków encaisse 58% de ses buts à l\'extérieur en seconde période, moment où Zagłębie est le plus prolifique.'
  },
  {
    league: 'POL',
    leagueFull: 'Ekstraklasa',
    home: 'Wisła Płock',
    away: 'Widzew Łódź',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '38% / 62%',
    color: 'badge-safe',
    scenario: 'Wisła Płock devrait verrouiller la première période grâce à sa défense de fer (0.45 but encaissé), avant de profiter de l\'effondrement physique habituel de Widzew après l\'heure de jeu.',
    trap: 'La "Nulite" aiguë de Płock : bien que favoris (55%), ils concèdent beaucoup de matchs nuls à domicile (4 sur 6), ce qui rend le pari sec risqué malgré la crise de Widzew.',
    score: '1-0',
    logic: 'Wisła Płock échoue à la règle du domicile (2V-4N). Le filtre "Diesel" est activé par la solidité défensive locale en 1ère MT et la friabilité de Widzew en fin de match (60% de buts encaissés en 2ème MT).'
  },
  {
    league: 'ROU',
    leagueFull: 'Liga I',
    home: 'Metaloglobus',
    away: 'Oţelul Galaţi',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '33% / 67%',
    color: 'badge-safe',
    scenario: 'Le bloc bas de Metaloglobus devrait résister un temps face à une équipe d\'Oţelul patiente, avant de céder physiquement et mentalement en seconde période.',
    trap: 'Le rythme d\'Oţelul : c\'est une équipe qui "bétonne" souvent en première mi-temps, ce qui peut mener à un score vierge à la pause malgré la faiblesse de l\'adversaire.',
    score: '0-2',
    logic: 'Metaloglobus est au fond du trou (0 victoire). Oţelul est solide mais pas flamboyant. La stat décisive est que Metaloglobus encaisse 65% de ses buts après la pause.'
  },
  {
    league: 'ROU',
    leagueFull: 'Liga I',
    home: 'Universitatea Cluj',
    away: 'Csikszereda',
    bet: 'Victoire de Universitatea Cluj',
    prob: '70%',
    rating: '75% / 25%',
    color: 'badge-safe',
    scenario: 'U. Cluj devrait imposer une domination totale dès le début pour effacer le souvenir du match aller, profitant des lacunes défensives criantes de Csikszereda à l\'extérieur.',
    trap: 'Le souvenir de l\'aller : Csikszereda avait surpris Cluj (2-1), mais c\'était une anomalie statistique que la forme actuelle à domicile de Cluj (4V/6) devrait corriger.',
    score: '3-0',
    logic: 'Application parfaite de la "Règle du Domicile" : U. Cluj a gagné 4 de ses 6 derniers matchs chez lui. Csikszereda possède l\'une des pires défenses (-27) et voyage très mal.'
  },
  {
    league: 'CYP',
    leagueFull: '1. Division',
    home: 'Akritas Chlorakas',
    away: 'Aris Limassol',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '27% / 73%',
    color: 'badge-safe',
    scenario: 'Aris va user la résistance d\'Akritas par sa possession, avant de concrétiser sa supériorité technique quand les locaux baisseront de pied physiquement.',
    trap: 'L\'irrégularité d\'Aris : capable de dominer mais de perdre sur des détails (comme contre l\'AEL), ce qui incite à éviter le résultat sec au profit des buts.',
    score: '1-3',
    logic: 'Akritas est faible (1V sur 6) mais Aris marque 65% de ses buts à l\'extérieur après la 50ème minute. Le scénario d\'une fin de match débridée est statistiquement le plus probable.'
  },
  {
    league: 'CYP',
    leagueFull: '1. Division',
    home: 'Omonia Nicosie',
    away: 'Enosis Paralimni',
    bet: 'Victoire d\'Omonia Nicosie',
    prob: '69%',
    rating: '93% / 7%',
    color: 'badge-safe',
    scenario: 'Une attaque-défense à sens unique où le leader Omonia devrait plier le match dès la première mi-temps face à une équipe qui n\'a pris qu\'un point cette saison.',
    trap: 'Aucun piège détectable : Enosis est la pire équipe du championnat (0 victoire, 46 buts encaissés) et Omonia est intraitable à domicile.',
    score: '4-0',
    logic: 'Le "Banker" absolu. Omonia valide la règle du domicile (4V/6) face à une lanterne rouge en perdition totale. L\'écart de niveau est abyssal (93% vs 7% en attaque).'
  },
  {
    league: 'CYP',
    leagueFull: '1. Division',
    home: 'AEK Larnaca',
    away: 'Apollon Limassol',
    bet: 'Plus de buts en 2ème mi-temps',
    prob: '80%',
    rating: '50% / 50%',
    color: 'badge-safe',
    scenario: 'Un sommet tactique et fermé en première période où la peur de perdre l\'emportera, avant que la fatigue et l\'enjeu n\'ouvrent des brèches tardives.',
    trap: 'La forme d\'Apollon : avec 9 victoires de suite, ils semblent invincibles, mais l\'AEK est leur bête noire (invaincu depuis 5 matchs), rendant le pari sur le vainqueur très hasardeux.',
    score: '1-1',
    logic: 'Larnaca ne gagne pas assez souvent à domicile pour être un pari sûr (3V/6). La stat clé est que 62% des buts de ces deux équipes sont inscrits après l\'heure de jeu.'
  },

]